server:
  servlet:
    context-path: /api

spring:
  application:
    name: release-tracker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/release_tracker_db}
    username: ${SPRING_DATASOURCE_USERNAME:release_tracker}
    password: ${SPRING_DATASOURCE_PASSWORD:release_tracker}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true

release-tracker:
  security:
    enabled: ${SECURITY_ENABLED:true}
    user:
      username: ${SECURITY_USER_USERNAME:user}
      password: ${SECURITY_USER_PASSWORD:user123}
    jwt-secret: ${SECURITY_JWT_SECRET:release-tracker--super-super-secret}